#!/usr/bin/python3

#TODO: Get possible_root_entries

import io

def bytes_to_ascii(byte_str):
    byte_str = byte_str.replace(b'\x00', b'')
    return byte_str.decode('ascii').rstrip()
    
def bytes_to_int(byte_str, order = 'little'):
    return int.from_bytes(byte_str, byteorder = order)

class Volume():
    EOF = [b'\xff\xff', b'\xf8\xff']

    def __init__(self, fname):
        self.vol = open(fname, "rb")
        self.read_boot_sector()
        self.determine_start_sectors()
        
    def read_boot_sector(self):
        self.vol.seek(3)
        self.oem_id = bytes_to_ascii(self.vol.read(8))
        self.bytes_per_sect = bytes_to_int(self.vol.read(2))
        self.sect_per_clust = bytes_to_int(self.vol.read(1))
        self.reserved_sect = bytes_to_int(self.vol.read(2))
        self.num_fat = bytes_to_int(self.vol.read(1))
        self.poss_root_entries = bytes_to_int(self.vol.read(2))
        self.vol.seek(22)
        self.sect_per_fat = bytes_to_int(self.vol.read(2))
        self.vol.seek(43)
        self.volume_label = bytes_to_ascii(self.vol.read(11))
        self.fs_type = bytes_to_ascii(self.vol.read(8))
    
    def determine_start_sectors(self):
        # Determine Start Sectors of Each Section
        self.reserved_region_start = 0
        self.fat_region_start = (self.reserved_region_start +
                                 self.sectors_to_bytes(self.reserved_sect))
        self.root_dir_start = (self.fat_region_start + 
                               self.sectors_to_bytes(self.num_fat * 
                                                     self.sect_per_fat))
        self.data_region_start = (self.root_dir_start + 
                                 self.sectors_to_bytes(self.calc_root_size()))
    
    def calc_root_size(self):
        root_entries_size = (self.poss_root_entries * 32) // self.bytes_per_sect
        root_entries_mod = (self.poss_root_entries * 32) % self.bytes_per_sect
        if root_entries_mod > 0:
            adjust = 1
        else:
            adjust = 0
        return root_entries_size + adjust
    
    def sectors_to_bytes(self, sectors):
        return sectors * self.bytes_per_sect
    
    def return_file(self, i_clust, fsize):
        file = b''
        fsize_sofar = 0
        
        i_clust = bytes(i_clust)
        
        while i_clust not in self.EOF:
            i_clust = bytes_to_int(i_clust)
            self.vol.seek(self.data_region_start + 
                          self.sectors_to_bytes(i_clust *
                                                self.sect_per_clust))
        
            fsize_sofar = fsize_sofar + self.bytes_per_sect
            if fsize_sofar > fsize:
                bytes_to_read = fsize_sofar - fsize
            else:
                bytes_to_read = self.bytes_per_sect
                
            file = file + self.vol.read(bytes_to_read)
        
            self.vol.seek(self.fat_region_start + 
                          self.sectors_to_bytes(i_clust))
            i_clust = self.vol.read(2)
            
   
        return file
    
    def print_info(self):
        print('Filesystem Type:      {0}'.format(self.fs_type))
        print('OEM ID:               {0}'.format(self.oem_id))
        print('Volume Label:         {0}'.format(self.volume_label))
        print('Bytes Per Sector:     {0}'.format(self.bytes_per_sect))
        print('Sectors Per Cluster:  {0}'.format(self.sect_per_clust))
        print('Reserved Sectors:     {0}'.format(self.reserved_sect))
        print('Number of FAT:        {0}'.format(self.num_fat))
        print('Sectors Per FAT:      {0}'.format(self.sect_per_fat))
        print('FAT Region Start:     {0}'.format(hex(self.fat_region_start)))
        print('Root Directory Start: {0}'.format(hex(self.root_dir_start)))
        print('Data Region Start:    {0}'.format(hex(self.data_region_start)))
        
class DirectoryEntry():
    def __init__(self, byte_str):
        self.dir_entry = io.BytesIO(byte_str)
        
        self.fname = bytes_to_ascii(self.dir_entry.read(8))
        self.f_ext = bytes_to_ascii(self.dir_entry.read(3))
        self.dir_entry.seek(-6, 2)
        self.starting_clust = bytes_to_int(self.dir_entry.read(2))
        self.filesize = bytes_to_int(self.dir_entry.read(4))
        
        self.filename = '{0}.{1}'.format(self.fname, self.f_ext)
        
    def print_info(self):
        print('Filename:        {0}'.format(self.filename))
        print('File Size:       {0}'.format(self.filesize))
        print('Starting Cluster {0}'.format(hex(self.starting_clust)))
        
v = Volume('fat-img-kw.dd')
v.print_info()

print()

v.vol.seek(v.root_dir_start + 32)
d = DirectoryEntry(v.vol.read(32))
d.print_info()

print()

f = v.return_file(d.starting_clust, d.filesize)

print('{0}'.format(f))
