#!/bin/sh

set -eu

GAMENAME="DOOM"
PLAYTIME_DIR=$HOME/Documents/Playtime

################################################################################
# Game-specific variables
DOOM_DIR=$HOME/Documents/Games/DOOM
################################################################################
 
start_time=$(expr $(date +%s) / 60)

# Command goes here...
chocolate-doom -iwad $DOOM_DIR/DOOM.WAD

end_time=$(expr $(date +%s) / 60)
playtime=$(expr $end_time - $start_time || true)

MONTH_DIR=$(date +%y-%m)
PLAYTIME_FILE=$(date +playtime-%y-%m-%d)

mkdir -p $PLAYTIME_DIR/$MONTH_DIR 2>/dev/null
echo "$playtime;$GAMENAME" >>\
    $PLAYTIME_DIR/$MONTH_DIR/$PLAYTIME_FILE
